// Run against a disposable app. PLAYWRIGHT_PATH selects the installed Playwright package.
const {chromium}=require(process.env.PLAYWRIGHT_PATH || 'playwright');
const fs=require('fs'); const path=require('path');
const out=__dirname;
if(process.env.RACELITH_AUDIT_DISPOSABLE!=='1')throw new Error('Set RACELITH_AUDIT_DISPOSABLE=1 only for the disposable audit instance.');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 const context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'Asia/Dubai'});
 const page=await context.newPage(); const errors=[]; const pageErrors=[]; const results=[];
 const record=(name,ok,evidence)=>{const r={name,status:ok?'PASS':'FAIL',evidence};results.push(r);console.log(JSON.stringify(r))};
 const api=async(method,p,data)=>{const r=await context.request.fetch('http://127.0.0.1:8000'+p,{method,data});return {status:r.status(),data:await r.json()}};
 page.on('pageerror',e=>{errors.push(e.message);pageErrors.push(e.message)});
 page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
 await page.goto('http://127.0.0.1:3000'); await page.waitForTimeout(1200);
 const sessionName='Browser Audit '+Date.now();
 await page.getByRole('button',{name:'← Back to Sessions',exact:true}).click();
 await page.getByRole('button',{name:'New Session',exact:true}).click();
 await page.locator('#session-name').fill(sessionName);
 await page.getByRole('button',{name:'Create Session',exact:true}).click();await page.waitForTimeout(600);
 record('Create session through UI',(await page.locator('body').innerText()).includes(sessionName),sessionName);
 record('Dashboard renders and WebSocket connects',(await page.locator('body').innerText()).includes('Live'),await page.locator('body').innerText());
 const log=async(karts,desc,penalty)=>{
  await page.locator('#kartNumber').fill(karts);
  await page.locator('#observer').fill('Browser Audit');
  await page.locator('#infringement').fill(desc);await page.keyboard.press('Escape');
  if(penalty){await page.locator('#penaltyDescription').fill(penalty);await page.keyboard.press('Escape')}
  await page.getByRole('button',{name:'Log Infringement',exact:true}).click();
  await page.waitForTimeout(400);
 };
 await log('71 72','Contact','10 Sec');
 let rows=(await api('GET','/infringements/')).data.items;
 record('Multi-kart form writes both records',rows.filter(x=>[71,72].includes(x.kart_number)).length===2,rows);
 record('Observer input does not overwrite turn number',rows.every(x=>x.turn_number===null),rows.map(x=>({kart:x.kart_number,turn:x.turn_number,observer:x.observer})));
 const observer=await context.newPage();await observer.goto('http://127.0.0.1:3000');await observer.waitForTimeout(500);
 for(let i=0;i<3;i++)await log('73','White Line Infringement');
 record('Second browser updates live',(await observer.locator('body').innerText()).includes('73'),await observer.locator('body').innerText());
 let pending=(await api('GET','/penalties/pending')).data;
 record('UI warnings create pending penalty',pending.some(x=>x.kart_number===73),pending);
 const penaltyRow=page.getByRole('row').filter({has:page.getByRole('button',{name:'Apply Penalty',exact:true})}).filter({hasText:'73'});
 await penaltyRow.getByRole('button',{name:'Apply Penalty',exact:true}).click();await page.waitForTimeout(400);
 record('UI applies individual penalty',!(await api('GET','/penalties/pending')).data.some(x=>x.kart_number===73),(await api('GET','/penalties/pending')).data);
 await page.getByRole('button',{name:'Qualifying: OFF',exact:true}).click();await page.waitForTimeout(250);
 await log('74','White Line Infringement');
 rows=(await api('GET','/infringements/')).data.items;
 record('Qualifying form assigns fastest lap invalidation',rows.find(x=>x.kart_number===74)?.penalty_description==='Fastest Lap Invalidation',rows.find(x=>x.kart_number===74));
 await page.getByRole('button',{name:'Qualifying: ON',exact:true}).click();
 const popPromise=context.waitForEvent('page');await page.getByRole('button',{name:'Open in new tab'}).click();const popup=await popPromise;await popup.waitForTimeout(700);
 record('Expanded log renders records',(await popup.locator('body').innerText()).includes('74'),await popup.locator('body').innerText());
 await popup.close();
 // A separate origin with an opener reference sends the popup deletion message.
 let victim=rows.find(x=>x.kart_number===72);
 const attackerPromise=context.waitForEvent('page');await page.evaluate(()=>window.open('http://localhost:3000'));const attacker=await attackerPromise;await attacker.waitForLoadState();
 await attacker.evaluate(id=>window.opener.postMessage({type:'deleteInfringement',id},'http://127.0.0.1:3000'),victim.id);
 await page.waitForTimeout(500);
 rows=(await api('GET','/infringements/')).data.items;
 record('Cross-origin popup messages cannot delete records',rows.some(x=>x.id===victim.id),{attackerOrigin:'http://localhost:3000',victimId:victim.id,exists:rows.some(x=>x.id===victim.id)});
 await attacker.close();
 // Simulate an actual failed save, then inspect whether the user's draft survives.
 await page.route('**/infringements/',route=>route.request().method()==='POST'?route.fulfill({status:500,contentType:'application/json',body:'{"detail":"Audit simulated failure"}'}):route.continue());
 await log('75','Contact','10 Sec');
 record('Failed submission retains form draft',(await page.locator('#kartNumber').inputValue())==='75',{kart:await page.locator('#kartNumber').inputValue(),errorVisible:(await page.locator('body').innerText()).includes('Audit simulated failure')});
 await page.unroute('**/infringements/');
 // Seed realistic pagination using real API writes, without mocking the app data layer.
 for(let batch=0;batch<11;batch++)await Promise.all(Array.from({length:10},(_,j)=>api('POST','/infringements/',{kart_number:2000+batch*10+j,description:'Contact',penalty_description:'Warning',observer:'Pagination audit'})));
 await page.reload();await page.waitForTimeout(600);await page.locator('#page-size').click();await page.getByRole('option',{name:'100',exact:true}).click();
 await page.waitForFunction(()=>document.body.innerText.includes('Page\n1\nof\n2'));
 // Last header button is the next-page control (verified from source).
 await page.locator('#kart-search').fill('71');await page.waitForTimeout(100);
 record('Kart search finds records beyond current page',!(await page.locator('body').innerText()).includes('No infringements found for kart #71'),{kart:71,existsInDatabase:(await api('GET','/infringements/?limit=1000')).data.items.some(x=>x.kart_number===71),visible:(await page.locator('tbody').last().innerText())});
 await page.locator('#kart-search').fill('');
 const next=page.locator('button').filter({has:page.locator('svg.lucide-chevron-right')});
 await next.click();await page.waitForTimeout(400);
 const before=await page.locator('tbody').last().getByRole('row').first().innerText();
 await page.screenshot({path:path.join(out,'pagination-before.png'),fullPage:true});
 await api('POST','/infringements/',{kart_number:9999,description:'Contact',penalty_description:'Warning'});await page.waitForTimeout(600);
 const after=await page.locator('tbody').last().getByRole('row').first().innerText();
 const body=await page.locator('body').innerText();
 record('Live update respects selected page and page size',!after.includes('9999'),{before,after,footer:body.match(/Showing .* entries/)?.[0],page:body.match(/Page\n\d+\nof\n\d+/)?.[0],rowCount:await page.locator('tbody').last().getByRole('row').count()});
 await page.screenshot({path:path.join(out,'pagination-after.png'),fullPage:true});
 await page.getByRole('button',{name:'← Back to Sessions',exact:true}).click();
 let sessionRow=page.getByRole('row').filter({hasText:sessionName});
 // Exercise the supported anchor-download fallback; headless Chrome cannot operate native save pickers.
 await page.evaluate(()=>delete window.showSaveFilePicker);
 const downloadPromise=page.waitForEvent('download');await sessionRow.getByRole('button',{name:'Export',exact:true}).click();const download=await downloadPromise;
 await download.saveAs(path.join(out,'browser-export.xlsx'));
 record('UI export fallback downloads workbook',!await download.failure(),{filename:download.suggestedFilename(),bytes:fs.statSync(path.join(out,'browser-export.xlsx')).size});
 const importName='Browser Imported '+Date.now();
 const csv=fs.readFileSync(path.join(out,'export.csv'),'utf8').replace('Name,Audit Main','Name,'+importName);
 fs.writeFileSync(path.join(out,'browser-import.csv'),csv);
 page.once('dialog',d=>d.accept());
 await page.getByRole('button',{name:'Import',exact:true}).click();await page.locator('#import-file').setInputFiles(path.join(out,'browser-import.csv'));
 await page.getByRole('button',{name:'Import Session',exact:true}).click();await page.waitForTimeout(600);
 record('UI imports CSV and navigates to imported session',(await page.locator('body').innerText()).includes(importName),{name:importName,sessions:(await api('GET','/session/')).data.sessions});
 await page.getByRole('button',{name:'← Back to Sessions',exact:true}).click();
 sessionRow=page.getByRole('row').filter({hasText:sessionName});
 await sessionRow.getByRole('button',{name:'Load',exact:true}).click();await page.waitForTimeout(500);
 record('UI loads existing session',(await page.locator('body').innerText()).includes(sessionName),sessionName);
 await page.getByRole('button',{name:'← Back to Sessions',exact:true}).click();
 sessionRow=page.getByRole('row').filter({hasText:importName});await sessionRow.locator('button').last().click();
 await page.getByRole('alertdialog').getByRole('button',{name:'Delete',exact:true}).click();await page.waitForTimeout(400);
 record('UI deletes disposable session',!(await api('GET','/session/')).data.sessions.some(x=>x.name===importName),importName);
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(200);
 await page.screenshot({path:path.join(out,'mobile-sessions.png'),fullPage:true});
 record('Mobile page has no document horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth})));
 await observer.close();
 record('No uncaught browser exceptions',pageErrors.length===0,pageErrors);
 fs.writeFileSync(path.join(out,'browser-results.json'),JSON.stringify(results,null,2));
 await page.screenshot({path:path.join(out,'browser-initial.png'),fullPage:true});
 fs.writeFileSync(path.join(out,'browser-errors.json'),JSON.stringify(errors,null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
